language: go
go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8

go_import_path: github.com/DATA-DOG/fastroute

script:
  - go vet ./...
  - go fmt ./...
  - go test -v -race -bench=. github.com/DATA-DOG/fastroute/mux
  - go test -v -race -bench=. -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
